config/routes.rb
Test4::Application.routes.draw do
  resources :users
  get "say/hello"

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        #format.html { redirect_to @user, :notice => 'User #{@user.name} was successfully created.' }
        format.html { redirect_to(users_url, :notice => "User #{@user.name} was successfully created.") }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(users_url, :notice => "User #{@user.name} was successfully updated.") }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    begin
     @user.destroy
     flash[:notice] = "User #{@user.name} deleted"
    rescue Exception => e
     flash[:notice] = e.message
    end

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test4</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/say/hello.html.erb
<h1>Say#hello</h1>
<p>Find me in app/views/say/hello.html.erb</p>

    <%= image_tag("/images/hoopypet.png", :width => 44, :height => 62) %>

app/views/users/_form.html.erb
<div class="depot_form">

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


 <fieldset>
   <legend>Enter User Details</legend>
    <div>
    <%= f.label :name %>:
    <%= f.text_field :name, :size => 40 %>
    </div>
    <div>
    <%= f.label :email, 'email' %>:
    <%= f.email_field :email, :size => 40 %>
    </div>
    <div>
    <%= f.submit %>
    </div>
 </fieldset>
<% end %>
</div>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Listing users</h1>

  <% if notice %>
        <p id="notice"><%= notice %></p>
  <% end %>


<table>
<% @users.each do |user| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td><%= user.id %></td>
    <td><b>Name:</b> <%= user.name %> <br />
        <b>Email:</b> <%= user.email %> <br />
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>